### ISSUE TITLE
 Glade checklist

### ISSUE THREAD

**Issue by joshbressers** [Brown-County-FIRST-Robotics/1716-2023-robot#128]
- [ ] mechanum drive forward
- [ ] mechanum drive backwards
- [ ] mechanum rotate left
- [ ] mechanum rotate right
- [ ] mechanum strafe left
- [ ] mechanum strafe right
- [ ] mechanum drive angleyty
- [ ] tank drive forward
- [ ] tank drive backwards
- [ ] tank rotate  left
- [ ] tank rotate right
- [ ] auto level
- [ ] autonomous backup
- [ ] 
- [ ]
