### ISSUE TITLE
Current Todo

### ISSUE THREAD

**Issue by cfinn68916** [Brown-County-FIRST-Robotics/1716-2023-robot#153]
- [ ] Get arm working
- [ ] Get arm raspi control working
- [x] Add gripper commands to arm raspi control
- [ ] Redo action linkages to incorporate `AwaitSetHeight` and `AsyncSetHeight`
- [ ] Add `Pickup()` action
