### ISSUE TITLE
Colin TODO

### ISSUE THREAD

**Issue by cfinn68916** [Brown-County-FIRST-Robotics/1716-2023-robot#159]
- [x] test DriveToPoint command
- [ ] add real placement positions
- [x] Make DriveToPoint use paths and trajectory 
- [ ] Add DriveToGamePiece
- [ ] tune DriveToGamePiece PID
- [x] Make a full autonomous routine
- [x] Add inverse kinematics to arm
- [ ] Add logging
- [ ] Add driver tuning to arm
- [ ] Add tests
- [ ] Find out if the Led bug is still there
