### ISSUE TITLE
2023 TODO

### ISSUE THREAD

**Issue by joshbressers** [Brown-County-FIRST-Robotics/1716-2023-robot#38]
TODO for the 2023 game

# Must have systems
- [x] #40
- [x] Pick up mechanism control
- [x] Place mechanism control

# Should have
- [x] Autonomous mode
- [x] Auto balance
- [ ] #65
- [x] #45
- [x] #53
- [x] Smart dashboard

# Nice to have
- [ ] Auto pick up code
- [ ] Auto place code
- [ ] Autonomous control of driving
- [x] #66
- [ ] Pole detection
- [ ] Detect free positions in community

# Stretch
- [ ] Play music
- [ ] Wiimote / Guitar hero support
- [ ] Death mode
