### ISSUE TITLE
Apriltag Todo

### ISSUE THREAD

**Issue by cfinn68916** [Brown-County-FIRST-Robotics/1716-2023-robot#70]
- [x] fix josh's apriltag problem (and fix calibration file)
- [x] convert everything to cm
- [x] add networktables docs
- [ ] add error_matrix
- [ ] add error threshold value
- [x] add apriltag positions
- [x] finish camera position work

If you are looking for more things to do, check for "TODO:" in any python files
